name: pyconde2018 
dependencies:
    - numpy
    - scipy
    - nose
    - sphinx
    - pydot-ng
    - theano
    - pygpu
    - pydot
    - graphviz
    - pip:
      - keras
      - PyUserInput
      - parameterized
      - pyscreenshot
      - opencv-python

